# Numpy in Python:

        --> Numpy is a python libraray used for working with arrays.
        
        --> Its also functions for working in domain of linear algebra,fourier transformation,and matrices.
        
        --> Numpy stands for numerical python.

        --> Its a third party library.

# Converting list into array:

In [56]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
print('The normal list value is :',a)
x = np.array(a)
print('The array value is:',x)

The normal list value is : [5, 9, 67, 67, 45, 3, 4, 54, 23]
The array value is: [ 5  9 67 67 45  3  4 54 23]


# Adding two list using numpy:

In [54]:
import numpy as np
npl1 = np.array([1,2,3,4])
npl2 = np.array([1,2,3,4])
npl3 = npl1 * npl2
print('The 1st list array value is :',npl1)
print('The 2nd list array value is :',npl2)
print('The adding value of two array is:',npl3)

The 1st list array value is : [1 2 3 4]
The 2nd list array value is : [1 2 3 4]
The adding value of two array is: [ 1  4  9 16]


# Finding Dimensions in numpy:

In [36]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(x)
print('The dimension of x valiue is : ',x.ndim)

[ 5  9 67 67 45  3  4 54 23]
The dimension of x valiue is :  1


In [37]:
import numpy as np
a = np.array([[2,3,4],[5,6,7]])
print(a)
print('The dimension of a value is : ',a.ndim)

[[2 3 4]
 [5 6 7]]
The dimension of a value is :  2


In [42]:
import numpy as np
a =np.array([[[2,1,4,3,5],[7,8,6,5,5],[4,5,6,5,4]]])
print(a)
print('the dimension of a value is :',a.ndim)

[[[2 1 4 3 5]
  [7 8 6 5 5]
  [4 5 6 5 4]]]
the dimension of a value is : 3


# Finding shape in numpy:

In [44]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(x)
print('The shape of the x value is :',x.shape)

[ 5  9 67 67 45  3  4 54 23]
The shape of the x value is : (9,)


# Reshape in Numpy:

In [6]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(x.reshape)

<built-in method reshape of numpy.ndarray object at 0x00000298250E0090>


# Finding Data Types in Python:

In [45]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(a)
print('The data type of a is :',x.dtype)

[5, 9, 67, 67, 45, 3, 4, 54, 23]
The data type of a is : int32


# Finding Size in Python:

In [46]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(a)
print('the size of the a value is:',x.size)

[5, 9, 67, 67, 45, 3, 4, 54, 23]
the size of the a value is: 9


# Finding Data Types True (or) False:

In [12]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(x.dtype=='float64')

False


In [15]:
import numpy as np
a = [5,9,67,67,45,3,4,54,23]
x = np.array(a)
print(x.dtype=='int32')

True


# Finding Maximum number in numpy:

In [48]:
import numpy as np
a =[3,5,4,2,5,4,3,1]
y = np.array(a)
print(a)
print('The maximum value of x is:',max(x))

[3, 5, 4, 2, 5, 4, 3, 1]
The maximum value of x is: 67


# Finding Minimum number in numpy:

In [50]:
import numpy as np
a =[5,8,4,5,2,5,6,4,3,0,9]
y = np.array(a)
print(a)
print('The minimum value of a is:',min(y))

[5, 8, 4, 5, 2, 5, 6, 4, 3, 0, 9]
The minimum value of a is: 0


# Sum of values in Numpy:

In [51]:
import numpy as np
a = [4,7,5,7,7,6,6,8,9,]
y =np.array(a)
print(a)
print('The sum value of a is:',np.sum(y))

[4, 7, 5, 7, 7, 6, 6, 8, 9]
The sum value of a is: 59


# Square root values in numpy:

In [27]:
import numpy as np
a = [9,4,5,2,9,8,7,9]
y = np.array(a)
print(np.sqrt(y))

[3.         2.         2.23606798 1.41421356 3.         2.82842712
 2.64575131 3.        ]


# Converting Integer into Complex:

In [66]:
import numpy as np
l=np.array([[2,3,4],[5,4,5]],dtype=complex)
print('The complex value of l:',l)

The complex value of l: [[2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 4.+0.j 5.+0.j]]


# Converting Integer into Float:

In [69]:
import numpy as np
l=np.array([[2,3,4,3],[6,5,6,5]],dtype=float)
print('The Float value of:',l)

The Float value of: [[2. 3. 4. 3.]
 [6. 5. 6. 5.]]


# Range Value in Numpy:

In [75]:
import numpy as np
l = np.arange(10)
print('The range of of 0 to 10 is:',l)

The range of of 0 to 10 is: [0 1 2 3 4 5 6 7 8 9]


In [77]:
import numpy as np
l = np.zeros((3,3))
print(l)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [79]:
import numpy as np
l = np.ones((3,3))
print(l)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Indexing & Slizing in numpy:

# Indexing.

        --> Indexing is mainly used for acess some particular value with the help of its position.
        
        --> We have two types of indexing in numpy.They are
                    1.Positive Indexing.
                    2.Negative Indexing.

# Positive Indexing.

        --> We are going to acess the value with the help of positive values.


In [62]:
import numpy as np
l =np.array([2,5,4,3,6,7,9,5,3,7,7,6])
print(l)
print('The second indexing value of x is:',l[2])

[2 5 4 3 6 7 9 5 3 7 7 6]
The second indexing value of x is: 4


In [80]:
import numpy as np
l = np.array([9,4,5,3,7,6,5,7,8])
print(l)
print('the forth indexing value of x is:',l[4])

[9 4 5 3 7 6 5 7 8]
the forth indexing value of x is: 7


# Negative Indexing:

        --> We are acess the value with the help of negative values.
        
        --> The majour difference between positive indexing and negative indexing is they going to acess the value reverse.
       

In [82]:
import numpy as np
l = np.array([5,3,6,7,8,6,8,5,6,8])
print(l)
print('The negative value of -5 indexing value is:',l[-5])

[5 3 6 7 8 6 8 5 6 8]
The negative value of -5 indexing value is: 6


In [84]:
import numpy as np
l = np.array([6,4,9,6,3,2,6,7,8,4])
print(l)
print('The negative value of -8 indexing value is:',l[-8])

[6 4 9 6 3 2 6 7 8 4]
The negative value of -8 indexing value is: 9


# Slizing in Numpy:

        --> Slizing is mainly used for acess the value inbetween some range.
        
        --> We are going to acess the value with starting position and ending position. 

In [85]:
import numpy as np
l = np.array([1,6,4,5,8,5,9,7,4,7,6,3,7,0,9,0,7])
print(l)
print('the slizing value is:',l[3:6])

[1 6 4 5 8 5 9 7 4 7 6 3 7 0 9 0 7]
the slizing value is: [5 8 5]


In [86]:
import numpy as np
l = np.array([6,4,5,8,7,9,1,3,2,6,4,7,9,4,5,6,7])
print(l)
print('The slizing value is:',l[2:7])

[6 4 5 8 7 9 1 3 2 6 4 7 9 4 5 6 7]
The slizing value is: [5 8 7 9 1]


# Increment the value in slizing:

In [87]:
import numpy as np
l = np.array([3,2,1,3,2,5,6,4,6,7,8,9,8,7,8,9,7,6,5,4,7,8,9,4])
print(l)
print('The slizing value with increment:',l[2:8:2])

[3 2 1 3 2 5 6 4 6 7 8 9 8 7 8 9 7 6 5 4 7 8 9 4]
The slizing value with increment: [1 2 6]
